on:
  push:
    branches:
    - "publish"
jobs:
  Publish_NPM:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: https://registry.npmjs.org

    # Patch version
    - run: echo "PKG_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
    - run: echo "CURR_VER=$(npm view ${{env.PKG_NAME}} version)" >> $GITHUB_ENV
    - run: npm --no-git-tag-version version ${{env.CURR_VER}}
    - run: npm --no-git-tag-version version patch
    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
